---
# tasks file for apigee-opdk-setup-axgroup-remove
- name: Assert that attributes are available.
  assert:
    that:
      - "ax_group is defined and ax_group | trim | length > 0"
      - "local_mgmt_ip is defined and local_mgmt_ip | trim | length > 0"
      - "opdk_user_email is defined and opdk_user_email | trim | length > 0"
      - "opdk_user_pass is defined and opdk_user_pass | trim | length > 0"
    msg: "Please provide the missing attribute"

- block:
  - name: Remove axgroup
    uri:
      user: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'
      method: DELETE
      body_format: json
      url: http://{{ local_mgmt_ip }}:8080/v1/analytics/groups/ax/{{ ax_group }}

  rescue:

  - name: Recover attempted removal of axgroup
    uri:
      user: '{{ opdk_user_email }}'
      password: '{{ opdk_user_pass }}'
      method: DELETE
      body_format: json
      url: http://127.0.0.1:8080/v1/analytics/groups/ax/{{ ax_group }}
    delegate_to: "{{ local_mgmt_ip | default(ansible_default_ipv4.address) }}"

